# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHKOXP3Kq9nchDu_GlGigqNdunmK11Ks
"""

import pandas as pd
import mlflow
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import os

# [Basic] Mengaktifkan pencatatan otomatis dari MLflow
mlflow.autolog()

def train_basic():
    # Pastikan path mengarah ke hasil preprocessing sebelumnya
    data_path = 'preprocessing/examscore_preprocessing_automate.csv'
    if not os.path.exists(data_path):
        print(f"File {data_path} tidak ditemukan!")
        return

    df = pd.read_csv(data_path)
    X = df.drop(columns=['exam_score'])
    y = df['exam_score']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # [Basic] Melatih model Scikit-Learn sederhana (Random Forest)
    with mlflow.start_run(run_name="Model_Basic_Autolog_Lokal"):
        model = RandomForestRegressor(n_estimators=50, random_state=42)
        model.fit(X_train, y_train)
        print("Basic Model Training Selesai. Cek folder 'mlruns' di laptop Anda.")

if __name__ == "__main__":
    train_basic()